//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AspNetCore.OData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SRResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SRResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.AspNetCore.OData.Properties.SRResources", typeof(SRResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HttpActionContext.ActionDescriptor is null..
        /// </summary>
        internal static string ActionContextMustHaveDescriptor {
            get {
                return ResourceManager.GetString("ActionContextMustHaveDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HttpActionContext.Request is null..
        /// </summary>
        internal static string ActionContextMustHaveRequest {
            get {
                return ResourceManager.GetString("ActionContextMustHaveRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HttpExecutedActionContext.Request is null..
        /// </summary>
        internal static string ActionExecutedContextMustHaveRequest {
            get {
                return ResourceManager.GetString("ActionExecutedContextMustHaveRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action &apos;{0}&apos; is not bound to the collection of entity. Only actions that are bound to entities can have action links..
        /// </summary>
        internal static string ActionNotBoundToCollectionOfEntity {
            get {
                return ResourceManager.GetString("ActionNotBoundToCollectionOfEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action &apos;{0}&apos; is not bound to an entity. Only actions that are bound to entities can have action links..
        /// </summary>
        internal static string ActionNotBoundToEntity {
            get {
                return ResourceManager.GetString("ActionNotBoundToEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} type of aggregation is not supported..
        /// </summary>
        internal static string AggregateKindNotSupported {
            get {
                return ResourceManager.GetString("AggregateKindNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregation method &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string AggregationMethodNotSupported {
            get {
                return ResourceManager.GetString("AggregationMethodNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregation &apos;{0}&apos; not supported for property &apos;{1}&apos; of type &apos;{2}&apos;..
        /// </summary>
        internal static string AggregationNotSupportedForType {
            get {
                return ResourceManager.GetString("AggregationNotSupportedForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $apply query options not supported for LINQ to SQL providers.
        /// </summary>
        internal static string ApplyQueryOptionNotSupportedForLinq2SQL {
            get {
                return ResourceManager.GetString("ApplyQueryOptionNotSupportedForLinq2SQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query option is not bound to any CLR type. &apos;{0}&apos; is only supported with a query option bound to a CLR type..
        /// </summary>
        internal static string ApplyToOnUntypedQueryOption {
            get {
                return ResourceManager.GetString("ApplyToOnUntypedQueryOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be greater than or equal to {0}..
        /// </summary>
        internal static string ArgumentMustBeGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("ArgumentMustBeGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be less than or equal to {0}..
        /// </summary>
        internal static string ArgumentMustBeLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("ArgumentMustBeLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument must be of type &apos;{0}&apos;..
        /// </summary>
        internal static string ArgumentMustBeOfType {
            get {
                return ResourceManager.GetString("ArgumentMustBeOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The batch request must have &apos;{0}&apos; or &apos;{1}&apos; as the media type..
        /// </summary>
        internal static string BatchRequestInvalidMediaType {
            get {
                return ResourceManager.GetString("BatchRequestInvalidMediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The batch request must have a boundary specification in the &quot;Content-Type&quot; header..
        /// </summary>
        internal static string BatchRequestMissingBoundary {
            get {
                return ResourceManager.GetString("BatchRequestMissingBoundary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Content&apos; property on the batch request cannot be null..
        /// </summary>
        internal static string BatchRequestMissingContent {
            get {
                return ResourceManager.GetString("BatchRequestMissingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The batch request must have a &quot;Content-Type&quot; header..
        /// </summary>
        internal static string BatchRequestMissingContentType {
            get {
                return ResourceManager.GetString("BatchRequestMissingContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A binary operator with incompatible types was detected. Found operand types &apos;{0}&apos; and &apos;{1}&apos; for operator kind &apos;{2}&apos;..
        /// </summary>
        internal static string BinaryOperatorNotSupported {
            get {
                return ResourceManager.GetString("BinaryOperatorNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; on type &apos;{1}&apos; returned a null value. The input stream contains collection items which cannot be added if the instance is null..
        /// </summary>
        internal static string CannotAddToNullCollection {
            get {
                return ResourceManager.GetString("CannotAddToNullCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot apply {0} of &apos;{1}&apos; to {2} of &apos;{3}&apos;..
        /// </summary>
        internal static string CannotApplyETagOfT {
            get {
                return ResourceManager.GetString("CannotApplyETagOfT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot apply {0} of &apos;{1}&apos; to {2} of &apos;{3}&apos;..
        /// </summary>
        internal static string CannotApplyODataQueryOptionsOfT {
            get {
                return ResourceManager.GetString("CannotApplyODataQueryOptionsOfT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot cast $filter of type &apos;{0}&apos; to type &apos;{1}&apos;..
        /// </summary>
        internal static string CannotCastFilter {
            get {
                return ResourceManager.GetString("CannotCastFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; does not exist on type &apos;{1}&apos;. Make sure to only use property names that are defined by the type..
        /// </summary>
        internal static string CannotDeserializeUnknownProperty {
            get {
                return ResourceManager.GetString("CannotDeserializeUnknownProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An instance of the abstract resource type &apos;{0}&apos; was found. Abstract resource types cannot be instantiated..
        /// </summary>
        internal static string CannotInstantiateAbstractResourceType {
            get {
                return ResourceManager.GetString("CannotInstantiateAbstractResourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot apply PATCH to navigation property &apos;{0}&apos; on entity type &apos;{1}&apos;..
        /// </summary>
        internal static string CannotPatchNavigationProperties {
            get {
                return ResourceManager.GetString("CannotPatchNavigationProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot serialize a null &apos;{0}&apos;..
        /// </summary>
        internal static string CannotSerializerNull {
            get {
                return ResourceManager.GetString("CannotSerializerNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dynamic dictionary property &apos;{0}&apos; of type &apos;{1}&apos; cannot be set. The dynamic property dictionary must have a setter..
        /// </summary>
        internal static string CannotSetDynamicPropertyDictionary {
            get {
                return ResourceManager.GetString("CannotSetDynamicPropertyDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot write an object of type &apos;{1}&apos;..
        /// </summary>
        internal static string CannotWriteType {
            get {
                return ResourceManager.GetString("CannotWriteType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given model does not contain the type &apos;{0}&apos;..
        /// </summary>
        internal static string ClrTypeNotInModel {
            get {
                return ResourceManager.GetString("ClrTypeNotInModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; of the parameter &apos;{1}&apos; does not have an Add method. Consider using a collection type that does have an Add method - for example IList&lt;T&gt; or ICollection&lt;T&gt;..
        /// </summary>
        internal static string CollectionParameterShouldHaveAddMethod {
            get {
                return ResourceManager.GetString("CollectionParameterShouldHaveAddMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; of the property &apos;{1}&apos; on type &apos;{2}&apos; does not have an Add method. Consider using a collection type that does have an Add method - for example IList&lt;T&gt; or ICollection&lt;T&gt;..
        /// </summary>
        internal static string CollectionShouldHaveAddMethod {
            get {
                return ResourceManager.GetString("CollectionShouldHaveAddMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; of the property &apos;{1}&apos; on type &apos;{2}&apos; does not have a Clear method. Consider using a collection type that does have a Clear method, such as IList&lt;T&gt; or ICollection&lt;T&gt;..
        /// </summary>
        internal static string CollectionShouldHaveClearMethod {
            get {
                return ResourceManager.GetString("CollectionShouldHaveClearMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot compare an enum of type &apos;{0}&apos; to an expression of type &apos;{1}&apos;..
        /// </summary>
        internal static string ConvertToEnumFailed {
            get {
                return ResourceManager.GetString("ConvertToEnumFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not support CreateODataValue..
        /// </summary>
        internal static string CreateODataValueNotSupported {
            get {
                return ResourceManager.GetString("CreateODataValueNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The actual entity type &apos;{0}&apos; is not assignable to the expected type &apos;{1}&apos;..
        /// </summary>
        internal static string DeltaEntityTypeNotAssignable {
            get {
                return ResourceManager.GetString("DeltaEntityTypeNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find nested resource name &apos;{0}&apos; in parent resource type &apos;{1}&apos;.
        /// </summary>
        internal static string DeltaNestedResourceNameNotFound {
            get {
                return ResourceManager.GetString("DeltaNestedResourceNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use Delta of type &apos;{0}&apos; on an entity of type &apos;{1}&apos;..
        /// </summary>
        internal static string DeltaTypeMismatch {
            get {
                return ResourceManager.GetString("DeltaTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; does not support Read..
        /// </summary>
        internal static string DeserializerDoesNotSupportRead {
            get {
                return ResourceManager.GetString("DeserializerDoesNotSupportRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; does not support ReadInline..
        /// </summary>
        internal static string DoesNotSupportReadInLine {
            get {
                return ResourceManager.GetString("DoesNotSupportReadInLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate dynamic property name &apos;{0}&apos; found in open type &apos;{1}&apos;. Each dynamic property name must be unique..
        /// </summary>
        internal static string DuplicateDynamicPropertyNameFound {
            get {
                return ResourceManager.GetString("DuplicateDynamicPropertyNameFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dynamic property &apos;{0}&apos; with Edm type &apos;{1}&apos; cannot be serialized..
        /// </summary>
        internal static string DynamicPropertyCannotBeSerialized {
            get {
                return ResourceManager.GetString("DynamicPropertyCannotBeSerialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of dynamic property &apos;{0}&apos; was already used as the declared property name of open type &apos;{1}&apos;..
        /// </summary>
        internal static string DynamicPropertyNameAlreadyUsedAsDeclaredPropertyName {
            get {
                return ResourceManager.GetString("DynamicPropertyNameAlreadyUsedAsDeclaredPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type name of the dynamic resource set &apos;{0}&apos; is required and cannot be empty. Consider using a OData type annotation explicitly..
        /// </summary>
        internal static string DynamicResourceSetTypeNameIsRequired {
            get {
                return ResourceManager.GetString("DynamicResourceSetTypeNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The edit link builder for the entity set &apos;{0}&apos; returned null. An edit link is required for the location header..
        /// </summary>
        internal static string EditLinkNullForLocationHeader {
            get {
                return ResourceManager.GetString("EditLinkNullForLocationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get property &apos;{0}&apos; of a null EDM object of type &apos;{1}&apos;..
        /// </summary>
        internal static string EdmComplexObjectNullRef {
            get {
                return ResourceManager.GetString("EdmComplexObjectNullRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;EdmObject&apos; of {0} cannot be null..
        /// </summary>
        internal static string EdmObjectNull {
            get {
                return ResourceManager.GetString("EdmObjectNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EDM type of the object of type &apos;{0}&apos; is null. The EDM type of an {1} cannot be null..
        /// </summary>
        internal static string EdmTypeCannotBeNull {
            get {
                return ResourceManager.GetString("EdmTypeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a supported EDM type..
        /// </summary>
        internal static string EdmTypeNotSupported {
            get {
                return ResourceManager.GetString("EdmTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;ElementClrType&apos; of {0} cannot be null..
        /// </summary>
        internal static string ElementClrTypeNull {
            get {
                return ResourceManager.GetString("ElementClrTypeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Uri &apos;{0}&apos; in the parameter is invalid..
        /// </summary>
        internal static string EntityReferenceMustHasKeySegment {
            get {
                return ResourceManager.GetString("EntityReferenceMustHasKeySegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The related entity set could not be found from the OData path. The related entity set is required to serialize the payload..
        /// </summary>
        internal static string EntitySetMissingDuringSerialization {
            get {
                return ResourceManager.GetString("EntitySetMissingDuringSerialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity type &apos;{0}&apos; does not match the expected entity type &apos;{1}&apos; as set on the query context..
        /// </summary>
        internal static string EntityTypeMismatch {
            get {
                return ResourceManager.GetString("EntityTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; is not supported by the ODataErrorSerializer. The type must be ODataError or HttpError..
        /// </summary>
        internal static string ErrorTypeMustBeODataErrorOrHttpError {
            get {
                return ResourceManager.GetString("ErrorTypeMustBeODataErrorOrHttpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ETag is not well-formed..
        /// </summary>
        internal static string ETagNotWellFormed {
            get {
                return ResourceManager.GetString("ETagNotWellFormed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $filter in $expand of reference navigation property &apos;{0}&apos; is not expected type &apos;{1}&apos;.
        /// </summary>
        internal static string ExpandFilterExpressionNotLambdaExpression {
            get {
                return ResourceManager.GetString("ExpandFilterExpressionNotLambdaExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create an EDM model as the action &apos;{0}&apos; on controller &apos;{1}&apos; has a void return type..
        /// </summary>
        internal static string FailedToBuildEdmModelBecauseReturnTypeIsNull {
            get {
                return ResourceManager.GetString("FailedToBuildEdmModelBecauseReturnTypeIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create an EDM model as the action &apos;{0}&apos; on controller &apos;{1}&apos; has a return type &apos;{2}&apos; that does not implement IEnumerable&lt;T&gt;..
        /// </summary>
        internal static string FailedToRetrieveTypeToBuildEdmModel {
            get {
                return ResourceManager.GetString("FailedToRetrieveTypeToBuildEdmModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading type &apos;{0}&apos; is not supported by &apos;{1}&apos;..
        /// </summary>
        internal static string FormatterReadIsNotSupportedForType {
            get {
                return ResourceManager.GetString("FormatterReadIsNotSupportedForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function &apos;{0}&apos; is not bound to the collection of entity. Only functions that are bound to entities can have function links..
        /// </summary>
        internal static string FunctionNotBoundToCollectionOfEntity {
            get {
                return ResourceManager.GetString("FunctionNotBoundToCollectionOfEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function &apos;{0}&apos; is not bound to an entity. Only functions that are bound to entities can have function links..
        /// </summary>
        internal static string FunctionNotBoundToEntity {
            get {
                return ResourceManager.GetString("FunctionNotBoundToEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; function cannot be applied to an enumeration-typed argument..
        /// </summary>
        internal static string FunctionNotSupportedOnEnum {
            get {
                return ResourceManager.GetString("FunctionNotSupportedOnEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the property &apos;{0}&apos; on type &apos;{1}&apos; is an array. Consider adding a setter for the property..
        /// </summary>
        internal static string GetOnlyCollectionCannotBeArray {
            get {
                return ResourceManager.GetString("GetOnlyCollectionCannotBeArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Id link builder for the entity set &apos;{0}&apos; returned null. An Id link is required for the OData-EntityId header..
        /// </summary>
        internal static string IdLinkNullForEntityIdHeader {
            get {
                return ResourceManager.GetString("IdLinkNullForEntityIdHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input cast type &apos;{0}&apos; does not match the expected type kind &apos;{1}&apos;..
        /// </summary>
        internal static string InputCastTypeKindNotMatch {
            get {
                return ResourceManager.GetString("InputCastTypeKindNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input key count &apos;{0}&apos; doesn&apos;t match the number of the entity type key &apos;{1}&apos;..
        /// </summary>
        internal static string InputKeyNotMatchEntityTypeKey {
            get {
                return ResourceManager.GetString("InputKeyNotMatchEntityTypeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current batch reader state &apos;{0}&apos; is invalid. The expected state is &apos;{1}&apos;..
        /// </summary>
        internal static string InvalidBatchReaderState {
            get {
                return ResourceManager.GetString("InvalidBatchReaderState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; should be less than or equal to &apos;{1}&apos;..
        /// </summary>
        internal static string InvalidExpansionDepthValue {
            get {
                return ResourceManager.GetString("InvalidExpansionDepthValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last segment &apos;{0}&apos; of the select or expand query option is not supported..
        /// </summary>
        internal static string InvalidLastSegmentInSelectExpandPath {
            get {
                return ResourceManager.GetString("InvalidLastSegmentInSelectExpandPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path template &apos;{0}&apos; on the action &apos;{1}&apos; in controller &apos;{2}&apos; is not a valid OData path template. {3}.
        /// </summary>
        internal static string InvalidODataRouteOnAction {
            get {
                return ResourceManager.GetString("InvalidODataRouteOnAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given untyped value &apos;{0}&apos; in payload is invalid. Consider using a OData type annotation explicitly..
        /// </summary>
        internal static string InvalidODataUntypedValue {
            get {
                return ResourceManager.GetString("InvalidODataUntypedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mapper provider must return a valid &apos;{0}&apos; instance for the given &apos;{1}&apos; IEdmType..
        /// </summary>
        internal static string InvalidPropertyMapper {
            get {
                return ResourceManager.GetString("InvalidPropertyMapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key mapping for the property &apos;{0}&apos; can&apos;t be null or empty..
        /// </summary>
        internal static string InvalidPropertyMapping {
            get {
                return ResourceManager.GetString("InvalidPropertyMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A segment &apos;{0}&apos; within the select or expand query option is not supported..
        /// </summary>
        internal static string InvalidSegmentInSelectExpandPath {
            get {
                return ResourceManager.GetString("InvalidSegmentInSelectExpandPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key property &apos;{0}&apos; of type &apos;{1}&apos; is null. Key properties cannot have null values..
        /// </summary>
        internal static string KeyValueCannotBeNull {
            get {
                return ResourceManager.GetString("KeyValueCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided mapping does not contain a resource for the resource type &apos;{0}&apos;..
        /// </summary>
        internal static string MappingDoesNotContainResourceType {
            get {
                return ResourceManager.GetString("MappingDoesNotContainResourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Any/All nesting limit of &apos;{0}&apos; has been exceeded. &apos;{1}&apos; can be configured on ODataQuerySettings or EnableQueryAttribute..
        /// </summary>
        internal static string MaxAnyAllExpressionLimitExceeded {
            get {
                return ResourceManager.GetString("MaxAnyAllExpressionLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request includes a $expand path which is too deep. The maximum depth allowed is {0}. To increase the limit, set the &apos;{1}&apos; property on EnableQueryAttribute or ODataValidationSettings, or set the &apos;MaxDepth&apos; property in ExpandAttribute..
        /// </summary>
        internal static string MaxExpandDepthExceeded {
            get {
                return ResourceManager.GetString("MaxExpandDepthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The node count limit of &apos;{0}&apos; has been exceeded. To increase the limit, set the &apos;{1}&apos; property on EnableQueryAttribute or ODataValidationSettings..
        /// </summary>
        internal static string MaxNodeLimitExceeded {
            get {
                return ResourceManager.GetString("MaxNodeLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the services container for the non-OData route. This can occur when using OData components on the non-OData route and is usually a configuration issue. Call EnableDependencyInjection() to enable OData components on non-OData routes. This may also occur when a request was mistakenly handled by the ASP.NET Core routing layer instead of the OData routing layer, for instance the URL does not include the OData route prefix configured via a call to MapODataServiceRoute()..
        /// </summary>
        internal static string MissingNonODataContainer {
            get {
                return ResourceManager.GetString("MissingNonODataContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the services container for route &apos;{0}&apos;. This should not happen and represents a bug..
        /// </summary>
        internal static string MissingODataContainer {
            get {
                return ResourceManager.GetString("MissingODataContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find &apos;{0}&apos;. The OData services have not been configured. Are you missing a call to AddOData()?.
        /// </summary>
        internal static string MissingODataServices {
            get {
                return ResourceManager.GetString("MissingODataServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The binding context cannot have a null ModelMetadata..
        /// </summary>
        internal static string ModelBinderUtil_ModelMetadataCannotBeNull {
            get {
                return ResourceManager.GetString("ModelBinderUtil_ModelMetadataCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The binding value &apos;{0}&apos; cannot be bound to the enum type &apos;{1}&apos;..
        /// </summary>
        internal static string ModelBinderUtil_ValueCannotBeEnum {
            get {
                return ResourceManager.GetString("ModelBinderUtil_ValueCannotBeEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EDM model is missing on the read context. The model is required on the read context to deserialize the payload..
        /// </summary>
        internal static string ModelMissingFromReadContext {
            get {
                return ResourceManager.GetString("ModelMissingFromReadContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one matching CLR type found for the EDM type {0}.\nThe matching CLR types are {1}..
        /// </summary>
        internal static string MultipleMatchingClrTypesForEdmType {
            get {
                return ResourceManager.GetString("MultipleMatchingClrTypesForEdmType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The related entity set or singleton cannot be found from the OData path. The related entity set or singleton is required to deserialize the payload..
        /// </summary>
        internal static string NavigationSourceMissingDuringDeserialization {
            get {
                return ResourceManager.GetString("NavigationSourceMissingDuringDeserialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The related entity set or singleton cannot be found from the OData path. The related entity set or singleton is required to serialize the payload..
        /// </summary>
        internal static string NavigationSourceMissingDuringSerialization {
            get {
                return ResourceManager.GetString("NavigationSourceMissingDuringSerialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; is a nested collection type. Nested collection types are not allowed..
        /// </summary>
        internal static string NestedCollectionsNotSupported {
            get {
                return ResourceManager.GetString("NestedCollectionsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find nested property &apos;{0}&apos; on the resource type &apos;{1}&apos;..
        /// </summary>
        internal static string NestedPropertyNotfound {
            get {
                return ResourceManager.GetString("NestedPropertyNotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested resource is not a collection. Query options $filter, $orderby, $count, $skip, and $top can be applied only on collections..
        /// </summary>
        internal static string NonSelectExpandOnSingleEntity {
            get {
                return ResourceManager.GetString("NonSelectExpandOnSingleEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arithmetic operator &apos;{0}&apos; is not allowed. To allow it, set the &apos;{1}&apos; property on EnableQueryAttribute or QueryValidationSettings..
        /// </summary>
        internal static string NotAllowedArithmeticOperator {
            get {
                return ResourceManager.GetString("NotAllowedArithmeticOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function &apos;{0}&apos; is not allowed. To allow it, set the &apos;{1}&apos; property on EnableQueryAttribute or QueryValidationSettings..
        /// </summary>
        internal static string NotAllowedFunction {
            get {
                return ResourceManager.GetString("NotAllowedFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical operator &apos;{0}&apos; is not allowed. To allow it, set the &apos;{1}&apos; property on EnableQueryAttribute or QueryValidationSettings..
        /// </summary>
        internal static string NotAllowedLogicalOperator {
            get {
                return ResourceManager.GetString("NotAllowedLogicalOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order by &apos;{0}&apos; is not allowed. To allow it, set the &apos;{1}&apos; property on EnableQueryAttribute or QueryValidationSettings..
        /// </summary>
        internal static string NotAllowedOrderByProperty {
            get {
                return ResourceManager.GetString("NotAllowedOrderByProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query option &apos;{0}&apos; is not allowed. To allow it, set the &apos;{1}&apos; property on EnableQueryAttribute or QueryValidationSettings..
        /// </summary>
        internal static string NotAllowedQueryOption {
            get {
                return ResourceManager.GetString("NotAllowedQueryOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity set &apos;{0}&apos; cannot be used for $count..
        /// </summary>
        internal static string NotCountableEntitySetUsedForCount {
            get {
                return ResourceManager.GetString("NotCountableEntitySetUsedForCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; cannot be used for $count..
        /// </summary>
        internal static string NotCountablePropertyUsedForCount {
            get {
                return ResourceManager.GetString("NotCountablePropertyUsedForCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; cannot be used in the $expand query option..
        /// </summary>
        internal static string NotExpandablePropertyUsedInExpand {
            get {
                return ResourceManager.GetString("NotExpandablePropertyUsedInExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; cannot be used in the $filter query option..
        /// </summary>
        internal static string NotFilterablePropertyUsedInFilter {
            get {
                return ResourceManager.GetString("NotFilterablePropertyUsedInFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; cannot be used for navigation..
        /// </summary>
        internal static string NotNavigablePropertyUsedInNavigation {
            get {
                return ResourceManager.GetString("NotNavigablePropertyUsedInNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; cannot be used in the $select query option..
        /// </summary>
        internal static string NotSelectablePropertyUsedInSelect {
            get {
                return ResourceManager.GetString("NotSelectablePropertyUsedInSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; cannot be used in the $orderby query option..
        /// </summary>
        internal static string NotSortablePropertyUsedInOrderBy {
            get {
                return ResourceManager.GetString("NotSortablePropertyUsedInOrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformation kind {0} is not supported..
        /// </summary>
        internal static string NotSupportedTransformationKind {
            get {
                return ResourceManager.GetString("NotSupportedTransformationKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The container built by the container builder must not be null..
        /// </summary>
        internal static string NullContainer {
            get {
                return ResourceManager.GetString("NullContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The container builder created by the container builder factory must not be null..
        /// </summary>
        internal static string NullContainerBuilder {
            get {
                return ResourceManager.GetString("NullContainerBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collections cannot contain null elements..
        /// </summary>
        internal static string NullElementInCollection {
            get {
                return ResourceManager.GetString("NullElementInCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown function &apos;{0}&apos;..
        /// </summary>
        internal static string ODataFunctionNotSupported {
            get {
                return ResourceManager.GetString("ODataFunctionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation cannot be completed because no ODataPath is available for the request..
        /// </summary>
        internal static string ODataPathMissing {
            get {
                return ResourceManager.GetString("ODataPathMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only ordering by properties is supported for non-primitive collections. Expressions are not supported..
        /// </summary>
        internal static string OrderByClauseNotSupported {
            get {
                return ResourceManager.GetString("OrderByClauseNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple &apos;$it&apos; nodes are not supported in &apos;$orderby&apos;..
        /// </summary>
        internal static string OrderByDuplicateIt {
            get {
                return ResourceManager.GetString("OrderByDuplicateIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate property named &apos;{0}&apos; is not supported in &apos;$orderby&apos;..
        /// </summary>
        internal static string OrderByDuplicateProperty {
            get {
                return ResourceManager.GetString("OrderByDuplicateProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of clauses in $orderby query option exceeded the maximum number allowed. The maximum number of $orderby clauses allowed is {0}..
        /// </summary>
        internal static string OrderByNodeCountExceeded {
            get {
                return ResourceManager.GetString("OrderByNodeCountExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; of the parameter &apos;{1}&apos; must be a collection..
        /// </summary>
        internal static string ParameterTypeIsNotCollection {
            get {
                return ResourceManager.GetString("ParameterTypeIsNotCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; of the property &apos;{1}&apos; on type &apos;{2}&apos; must be a collection..
        /// </summary>
        internal static string PropertyIsNotCollection {
            get {
                return ResourceManager.GetString("PropertyIsNotCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be a boolean..
        /// </summary>
        internal static string PropertyMustBeBoolean {
            get {
                return ResourceManager.GetString("PropertyMustBeBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be a DateTimeOffset or Date..
        /// </summary>
        internal static string PropertyMustBeDateTimeOffsetOrDate {
            get {
                return ResourceManager.GetString("PropertyMustBeDateTimeOffsetOrDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value with type &apos;{0}&apos; must have type &apos;{1}&apos;..
        /// </summary>
        internal static string PropertyMustBeEnum {
            get {
                return ResourceManager.GetString("PropertyMustBeEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be a string..
        /// </summary>
        internal static string PropertyMustBeString {
            get {
                return ResourceManager.GetString("PropertyMustBeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be a string with a length of 1..
        /// </summary>
        internal static string PropertyMustBeStringLengthOne {
            get {
                return ResourceManager.GetString("PropertyMustBeStringLengthOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be a string with a maximum length of 1..
        /// </summary>
        internal static string PropertyMustBeStringMaxLengthOne {
            get {
                return ResourceManager.GetString("PropertyMustBeStringMaxLengthOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be a Edm.TimeOfDay..
        /// </summary>
        internal static string PropertyMustBeTimeOfDay {
            get {
                return ResourceManager.GetString("PropertyMustBeTimeOfDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EDM instance of type &apos;{0}&apos; is missing the property &apos;{1}&apos;..
        /// </summary>
        internal static string PropertyNotFound {
            get {
                return ResourceManager.GetString("PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property or path {0} isn&apos;t available in the current context. It was removed in earlier transformation..
        /// </summary>
        internal static string PropertyOrPathWasRemovedFromContext {
            get {
                return ResourceManager.GetString("PropertyOrPathWasRemovedFromContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for OData query &apos;{0}&apos; cannot be empty..
        /// </summary>
        internal static string QueryCannotBeEmpty {
            get {
                return ResourceManager.GetString("QueryCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A model is required for querying. Consider implementing the EnableQueryAttribute.GetModel method never to return a null value..
        /// </summary>
        internal static string QueryGetModelMustNotReturnNull {
            get {
                return ResourceManager.GetString("QueryGetModelMustNotReturnNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding OData QueryNode of kind {0} is not supported by {1}..
        /// </summary>
        internal static string QueryNodeBindingNotSupported {
            get {
                return ResourceManager.GetString("QueryNodeBindingNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating OData QueryNode of kind {0} is not supported by {1}..
        /// </summary>
        internal static string QueryNodeValidationNotSupported {
            get {
                return ResourceManager.GetString("QueryNodeValidationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query parameter &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string QueryParameterNotSupported {
            get {
                return ResourceManager.GetString("QueryParameterNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OData formatter requires an attached request in order to deserialize. Controller classes must derive from ODataController or be marked with ODataFormattingAttribute. Custom parameter bindings must call GetPerRequestFormatterInstance on each formatter and use these per-request instances..
        /// </summary>
        internal static string ReadFromStreamAsyncMustHaveRequest {
            get {
                return ResourceManager.GetString("ReadFromStreamAsyncMustHaveRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found unexpected parameter &apos;{0}&apos;..
        /// </summary>
        internal static string ReferenceNavigationPropertyExpandFilterVisitorUnexpectedParameter {
            get {
                return ResourceManager.GetString("ReferenceNavigationPropertyExpandFilterVisitorUnexpectedParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request must have an associated EDM model. Consider using the extension method HttpConfiguration.MapODataServiceRoute to register a route that parses the OData URI and attaches the model information..
        /// </summary>
        internal static string RequestMustHaveModel {
            get {
                return ResourceManager.GetString("RequestMustHaveModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last segment of the request URI &apos;{0}&apos; was not recognized as an OData action..
        /// </summary>
        internal static string RequestNotActionInvocation {
            get {
                return ResourceManager.GetString("RequestNotActionInvocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the resource type &apos;{0}&apos; in the model..
        /// </summary>
        internal static string ResourceTypeNotInModel {
            get {
                return ResourceManager.GetString("ResourceTypeNotInModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;RootElementName&apos; property is required on &apos;{0}&apos;..
        /// </summary>
        internal static string RootElementNameMissing {
            get {
                return ResourceManager.GetString("RootElementNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;select&apos; and &apos;expand&apos; cannot be both null or empty..
        /// </summary>
        internal static string SelectExpandEmptyOrNull {
            get {
                return ResourceManager.GetString("SelectExpandEmptyOrNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $select does not support selections of type &apos;{0}&apos;..
        /// </summary>
        internal static string SelectionTypeNotSupported {
            get {
                return ResourceManager.GetString("SelectionTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; is not a structured type. Only structured types support $select and $expand..
        /// </summary>
        internal static string SelectNonStructured {
            get {
                return ResourceManager.GetString("SelectNonStructured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action &apos;{0}&apos; on controller &apos;{1}&apos; returned a {2} containing more than one element. {2} must have zero or one elements..
        /// </summary>
        internal static string SingleResultHasMoreThanOneEntity {
            get {
                return ResourceManager.GetString("SingleResultHasMoreThanOneEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse the skiptoken value. Skiptoken value should always be server generated..
        /// </summary>
        internal static string SkipTokenParseError {
            get {
                return ResourceManager.GetString("SkipTokenParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The limit of &apos;{0}&apos; for {1} query has been exceeded. The value from the incoming request is &apos;{2}&apos;..
        /// </summary>
        internal static string SkipTopLimitExceeded {
            get {
                return ResourceManager.GetString("SkipTopLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A request container already exists on the request..
        /// </summary>
        internal static string SubRequestServiceProviderAlreadyExists {
            get {
                return ResourceManager.GetString("SubRequestServiceProviderAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; cannot be deserialized using the ODataMediaTypeFormatter..
        /// </summary>
        internal static string TypeCannotBeDeserialized {
            get {
                return ResourceManager.GetString("TypeCannotBeDeserialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; cannot be serialized using the ODataMediaTypeFormatter..
        /// </summary>
        internal static string TypeCannotBeSerialized {
            get {
                return ResourceManager.GetString("TypeCannotBeSerialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not an entity type. Only entity types are supported..
        /// </summary>
        internal static string TypeMustBeEntity {
            get {
                return ResourceManager.GetString("TypeMustBeEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; must be an enum or Nullable&lt;T&gt; where T is an enum type..
        /// </summary>
        internal static string TypeMustBeEnumOrNullableEnum {
            get {
                return ResourceManager.GetString("TypeMustBeEnumOrNullableEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; does not inherit from and is not a base type of &apos;{1}&apos;..
        /// </summary>
        internal static string TypeMustBeRelated {
            get {
                return ResourceManager.GetString("TypeMustBeRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a resource set type. Only resource set are supported..
        /// </summary>
        internal static string TypeMustBeResourceSet {
            get {
                return ResourceManager.GetString("TypeMustBeResourceSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; of dynamic property &apos;{1}&apos; is not supported..
        /// </summary>
        internal static string TypeOfDynamicPropertyNotSupported {
            get {
                return ResourceManager.GetString("TypeOfDynamicPropertyNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ODataMediaTypeFormatter was unable to determine the base URI for the request. The request must be processed by an OData route for the OData formatter to serialize the response..
        /// </summary>
        internal static string UnableToDetermineBaseUrl {
            get {
                return ResourceManager.GetString("UnableToDetermineBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ODataMediaTypeFormatter must be able to determine the metadata URL for a request in order to serialize the response..
        /// </summary>
        internal static string UnableToDetermineMetadataUrl {
            get {
                return ResourceManager.GetString("UnableToDetermineMetadataUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating OData UnaryOperatorNode of kind {0} is not supported by {1}..
        /// </summary>
        internal static string UnaryNodeValidationNotSupported {
            get {
                return ResourceManager.GetString("UnaryNodeValidationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element type &apos;{0}&apos; of the given collection type &apos;{1}&apos; is not of the type &apos;{2}&apos;..
        /// </summary>
        internal static string UnexpectedElementType {
            get {
                return ResourceManager.GetString("UnexpectedElementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EDM type &apos;{0}&apos; of kind &apos;{1}&apos; is not supported..
        /// </summary>
        internal static string UnsupportedEdmType {
            get {
                return ResourceManager.GetString("UnsupportedEdmType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found unsupported EdmTypeKind &apos;{0}&apos; in list of available types..
        /// </summary>
        internal static string UnsupportedEdmTypeKind {
            get {
                return ResourceManager.GetString("UnsupportedEdmTypeKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function &apos;{0}&apos; is already bound to another method..
        /// </summary>
        internal static string UriFunctionClrBinderAlreadyBound {
            get {
                return ResourceManager.GetString("UriFunctionClrBinderAlreadyBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query specified in the URI is not valid. {0}.
        /// </summary>
        internal static string UriQueryStringInvalid {
            get {
                return ResourceManager.GetString("UriQueryStringInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is invalid. {1}.
        /// </summary>
        internal static string ValueIsInvalid {
            get {
                return ResourceManager.GetString("ValueIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not support WriteObjectInline..
        /// </summary>
        internal static string WriteObjectInlineNotSupported {
            get {
                return ResourceManager.GetString("WriteObjectInlineNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not support WriteObject..
        /// </summary>
        internal static string WriteObjectNotSupported {
            get {
                return ResourceManager.GetString("WriteObjectNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OData formatter does not support writing client requests. This formatter instance must have an associated request..
        /// </summary>
        internal static string WriteToStreamAsyncMustHaveRequest {
            get {
                return ResourceManager.GetString("WriteToStreamAsyncMustHaveRequest", resourceCulture);
            }
        }
    }
}
